openapi: 3.0.3
info:
paths:

components:
  schemas:

    NftActivities:
      required:
        - items
      type: object
      properties:
        continuation:
          type: string
          description: Continuation token to paginate items search result
        items:
          type: array
          description: List of found activities
          items:
            "$ref": "#/components/schemas/NftActivity"

    NftCollection:
      required:
        - features
        - id
        - name
        - type
        - supportsLazyMint
      type: object
      properties:
        id:
          "$ref": "#/components/schemas/Address"
        type:
          type: string
          description: "Collection type"
          enum:
            - ERC721
            - ERC1155
            - CRYPTO_PUNKS
        owner:
          "$ref": "#/components/schemas/Address"
        name:
          type: string
          description: "Collection name"
        symbol:
          type: string
          description: "Collection symbol"
        features:
          type: array
          description: "Set of supported features for this collection"
          items:
            type: string
            enum:
              - APPROVE_FOR_ALL
              - SET_URI_PREFIX
              - BURN
              - MINT_WITH_ADDRESS
              - SECONDARY_SALE_FEES
              - MINT_AND_TRANSFER
        supportsLazyMint:
          type: boolean
          description: "Does the collection support lazy mint or not"
        minters:
          type: array
          description: "List of addresses that can mint items in this collection"
          items:
            "$ref": "#/components/schemas/Address"

    NftCollections:
      required:
        - total
        - collections
      type: object
      properties:
        total:
          type: integer
          description: Number of collections were found by request
          format: int64
        continuation:
          type: string
          description: Continuation token to paginate items search result
        collections:
          type: array
          description: List of found collections
          items:
            "$ref": "#/components/schemas/NftCollection"

    NftCollectionEvent:
      required:
        - eventId
        - id
      properties:
        eventId:
          type: string
        id:
          $ref: '#/components/schemas/Address'
      oneOf:
        - $ref: '#/components/schemas/NftCollectionUpdateEvent'

    NftCollectionUpdateEvent:
      type: object
      required:
        - collection
      properties:
        type:
          type: string
          enum:
            - UPDATE
        collection:
          $ref: '#/components/schemas/NftCollection'

    NftSignature:
      required:
        - r
        - s
        - v
      type: object
      properties:
        v:
          type: integer
        r:
          "$ref": "#/components/schemas/Binary"
        s:
          "$ref": "#/components/schemas/Binary"
    NftTokenId:
      required:
        - signature
        - tokenId
      type: object
      properties:
        tokenId:
          "$ref": "#/components/schemas/BigInteger"
        signature:
          "$ref": "#/components/schemas/NftSignature"

    NftItemFilter:
      type: object
      required:
        - sort
      properties:
        sort:
          type: string
          enum:
            - LAST_UPDATE
      oneOf:
        - $ref: "#/components/schemas/NftItemFilterAll"
        - $ref: "#/components/schemas/NftItemFilterByOwner"
        - $ref: "#/components/schemas/NftItemFilterByCreator"
        - $ref: "#/components/schemas/NftItemFilterByCollection"
    NftItemFilterAll:
      type: object
      required:
        - "@type"
        - showDeleted
      properties:
        "@type":
          type: string
          enum:
            - all
        showDeleted:
          type: boolean
        lastUpdatedFrom:
          type: string
          format: date-time
    NftItemFilterByOwner:
      type: object
      required:
        - "@type"
        - owner
      properties:
        "@type":
          type: string
          enum:
            - by_owner
        owner:
          $ref: "#/components/schemas/Address"

    NftItemFilterByCreator:
      type: object
      required:
        - "@type"
        - creator
      properties:
        "@type":
          type: string
          enum:
            - by_creator
        creator:
          $ref: "#/components/schemas/Address"

    NftItemFilterByCollection:
      type: object
      required:
        - "@type"
        - collection
      properties:
        "@type":
          type: string
          enum:
            - by_collection
        collection:
          $ref: "#/components/schemas/Address"

    NftOwnershipFilter:
      type: object
      required:
        - sort
      properties:
        sort:
          type: string
          enum:
            - LAST_UPDATE
      oneOf:
        - $ref: "#/components/schemas/NftOwnershipFilterAll"
        - $ref: "#/components/schemas/NftOwnershipFilterByOwner"
        - $ref: "#/components/schemas/NftOwnershipFilterByCreator"
        - $ref: "#/components/schemas/NftOwnershipFilterByCollection"
        - $ref: "#/components/schemas/NftOwnershipFilterByItem"
    NftOwnershipFilterAll:
      type: object
      required:
        - "@type"
      properties:
        "@type":
          type: string
          enum:
            - all
    NftOwnershipFilterByOwner:
      type: object
      required:
        - "@type"
        - owner
      properties:
        "@type":
          type: string
          enum:
            - by_owner
        owner:
          $ref: "#/components/schemas/Address"
    NftOwnershipFilterByCreator:
      type: object
      required:
        - "@type"
        - creator
      properties:
        "@type":
          type: string
          enum:
            - by_creator
        creator:
          $ref: "#/components/schemas/Address"
    NftOwnershipFilterByCollection:
      type: object
      required:
        - "@type"
        - collection
      properties:
        "@type":
          type: string
          enum:
            - by_collection
        collection:
          $ref: "#/components/schemas/Address"

    NftOwnershipFilterByItem:
      type: object
      required:
        - "@type"
        - contract
        - tokenId
      properties:
        "@type":
          type: string
          enum:
            - by_item
        contract:
          $ref: "#/components/schemas/Address"
        tokenId:
          $ref: "#/components/schemas/BigInteger"

    NftSort:
      type: object
      required:
        - property
        - direction
      properties:
        property:
          type: string
        direction:
          type: string
          enum:
            - ASC
            - DESC

    NftItem:
      required:
        - id
        - contract
        - tokenId
        - creators
        - supply
        - lazySupply
        - owners
        - royalties
      type: object
      properties:
        id:
          type: string
          description: Item identifier, has format '${contract}:${tokenId}'
        contract:
          "$ref": "#/components/schemas/Address"
        tokenId:
          "$ref": "#/components/schemas/BigInteger"
        creators:
          type: array
          description: Creators of the target item
          items:
            "$ref": "#/components/schemas/Part"
        supply:
          "$ref": "#/components/schemas/BigInteger"
        lazySupply:
          "$ref": "#/components/schemas/BigInteger"
        owners:
          type: array
          description: Owners of the target items
          items:
            "$ref": "#/components/schemas/Address"
        royalties:
          type: array
          description: List of royalties
          items:
            "$ref": "#/components/schemas/Part"
        date:
          type: string
          format: date-time
          description: "Data when the item was created"
        pending:
          type: array
          description: "Pending information about the item"
          items:
            "$ref": "#/components/schemas/ItemTransfer"
        deleted:
          type: boolean
          description: "Item was deleted or not"
        meta:
          "$ref": "#/components/schemas/NftItemMeta"
    NftItemAttribute:
      required:
        - key
      type: object
      properties:
        key:
          type: string
        value:
          type: string
        type:
          type: string
        format:
          type: string
    NftItemRoyalty:
      required:
        - account
        - value
      type: object
      properties:
        account:
          "$ref": "#/components/schemas/Address"
        value:
          type: integer
    NftDeletedItem:
      required:
        - id
        - token
        - tokenId
      type: object
      properties:
        id:
          type: string
          description: Item identifier, has format '${contract}:${tokenId}'
        token:
          "$ref": "#/components/schemas/Address"
        tokenId:
          "$ref": "#/components/schemas/BigInteger"

    NftItemEvent:
      required:
        - eventId
        - itemId
      properties:
        eventId:
          type: string
        itemId:
          type: string
      oneOf:
        - $ref: "#/components/schemas/NftItemUpdateEvent"
        - $ref: "#/components/schemas/NftItemDeleteEvent"
    NftItemUpdateEvent:
      type: object
      required:
        - item
      properties:
        type:
          type: string
          enum:
            - UPDATE
        item:
          $ref: "#/components/schemas/NftItem"
    NftItemDeleteEvent:
      type: object
      required:
        - item
      properties:
        type:
          type: string
          enum:
            - DELETE
        item:
          $ref: "#/components/schemas/NftDeletedItem"

    NftItems:
      required:
        - total
        - items
      type: object
      properties:
        total:
          type: integer
          description: "The total number of items satisfy the query"
          format: int64
        continuation:
          type: string
          description: "Continuation token from the previous response"
        items:
          type: array
          description: "List of found items"
          items:
            "$ref": "#/components/schemas/NftItem"
    NftItemMeta:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          description: "Name of the NFT item"
        description:
          type: string
          description: "Description of the NFT item"
        attributes:
          type: array
          description: "Attributes of the NFT item"
          items:
            "$ref": "#/components/schemas/NftItemAttribute"
        image:
          "$ref": "#/components/schemas/NftMedia"
        animation:
          "$ref": "#/components/schemas/NftMedia"
    NftItemRoyaltyList:
      type: object
      properties:
        royalty:
          type: array
          items:
            "$ref": "#/components/schemas/NftItemRoyalty"
    NftMedia:
      required:
        - meta
        - url
      type: object
      properties:
        url:
          type: object
          description: "URL address of the NFT media"
          additionalProperties:
            type: string
        meta:
          type: object
          description: "Meta of the NFT media"
          additionalProperties:
            "$ref": "#/components/schemas/NftMediaMeta"
    NftMediaMeta:
      required:
        - type
      type: object
      properties:
        type:
          type: string
          description: "NFT media type"
        width:
          type: integer
          format: int32
          description: "Width of the NFT image/video"
        height:
          type: integer
          format: int32
          description: "Height of the NFT image/video"

    LazyNft:
      type: object
      required:
        - contract
        - tokenId
        - uri
        - creators
        - royalties
        - signatures
      properties:
        contract:
          "$ref": "#/components/schemas/Address"
        tokenId:
          "$ref": "#/components/schemas/BigInteger"
        uri:
          type: string
          description: "Uniform Resource Identifier of the token"
        creators:
          type: array
          description: "Addresses of the NFT item creators"
          items:
            "$ref": "#/components/schemas/Part"
        royalties:
          type: array
          description: "List of royalties"
          items:
            "$ref": "#/components/schemas/Part"
        signatures:
          type: array
          description: "Digital signatures"
          items:
            "$ref": "#/components/schemas/Binary"
      description: Type of an Asset
      oneOf:
        - "$ref": "#/components/schemas/LazyErc721"
        - "$ref": "#/components/schemas/LazyErc1155"

    BurnLazyNftForm:
      type: object
      required:
        - creators
        - signatures
      properties:
        creators:
          type: array
          description: "Address of the NFT item creators"
          items:
            "$ref": "#/components/schemas/Address"
        signatures:
          type: array
          description: "Digital signatures"
          items:
            "$ref": "#/components/schemas/Binary"

    LazyErc1155:
      type: object
      required:
        - "@type"
        - supply
      properties:
        "@type":
          type: string
          enum:
            - ERC1155
        supply:
          "$ref": "#/components/schemas/BigInteger"
    LazyErc721:
      type: object
      required:
        - "@type"
      properties:
        "@type":
          type: string
          enum:
            - ERC721

    NftDeletedOwnership:
      required:
        - id
        - token
        - tokenId
        - owner
      type: object
      properties:
        id:
          type: string
          description: Ownership identifier, has format '${token}:${tokenId}:${owner}'
        token:
          "$ref": "#/components/schemas/Address"
        tokenId:
          "$ref": "#/components/schemas/BigInteger"
        owner:
          "$ref": "#/components/schemas/Address"
    NftOwnership:
      required:
        - id
        - contract
        - tokenId
        - owner
        - creators
        - value
        - lazyValue
        - date
        - pending
      type: object
      properties:
        id:
          type: string
          description: Ownership identifier, has format '${token}:${tokenId}:${owner}'
        contract:
          "$ref": "#/components/schemas/Address"
        tokenId:
          "$ref": "#/components/schemas/BigInteger"
        owner:
          "$ref": "#/components/schemas/Address"
        creators:
          type: array
          description: Creators of the target item
          items:
            "$ref": "#/components/schemas/Part"
        value:
          "$ref": "#/components/schemas/BigInteger"
        lazyValue:
          "$ref": "#/components/schemas/BigInteger"
        date:
          type: string
          description: Start date of ownership
          format: date-time
        pending:
          type: array
          description: History of ownership
          items:
            "$ref": "#/components/schemas/ItemHistory"

    NftOwnershipEvent:
      required:
        - eventId
        - ownershipId
      properties:
        eventId:
          type: string
        ownershipId:
          type: string
      oneOf:
        - $ref: "#/components/schemas/NftOwnershipUpdateEvent"
        - $ref: "#/components/schemas/NftOwnershipDeleteEvent"
    NftOwnershipUpdateEvent:
      type: object
      required:
        - ownership
      properties:
        type:
          type: string
          enum:
            - UPDATE
        ownership:
          $ref: "#/components/schemas/NftOwnership"
    NftOwnershipDeleteEvent:
      type: object
      required:
        - ownership
      properties:
        type:
          type: string
          enum:
            - DELETE
        ownership:
          $ref: "#/components/schemas/NftDeletedOwnership"

    NftOwnerships:
      required:
        - ownerships
        - total
      type: object
      properties:
        total:
          type: integer
          description: Number of ownerships were found by request
          format: int64
        continuation:
          type: string
          description: Continuation token to paginate Ownerships search result
        ownerships:
          type: array
          description: List of found ownerships
          items:
            "$ref": "#/components/schemas/NftOwnership"

    NftMediaSize:
      type: string
      enum:
        - ORIGINAL
        - BIG
        - PREVIEW
