openapi: 3.0.3
info:
paths:

components:
  schemas:

    NftActivities:
      required:
        - items
      type: object
      properties:
        continuation:
          type: string
          description: Continuation token to paginate items search result
        items:
          type: array
          description: List of found activities
          items:
            "$ref": "#/components/schemas/NftActivity"

    NftCollection:
      required:
        - features
        - id
        - name
        - type
        - supportsLazyMint
      type: object
      properties:
        id:
          "$ref": "#/components/schemas/Address"
        type:
          type: string
          description: "Collection type"
          enum:
            - ERC721
            - ERC1155
            - CRYPTO_PUNKS
        status:
          type: string
          description: "Collection status"
          enum:
            - PENDING
            - ERROR
            - CONFIRMED
        owner:
          "$ref": "#/components/schemas/Address"
        name:
          type: string
          description: "Collection name"
        symbol:
          type: string
          description: "Collection symbol"
        features:
          type: array
          description: "Set of supported features for this collection"
          items:
            type: string
            enum:
              - APPROVE_FOR_ALL
              - SET_URI_PREFIX
              - BURN
              - MINT_WITH_ADDRESS
              - SECONDARY_SALE_FEES
              - MINT_AND_TRANSFER
        supportsLazyMint:
          type: boolean
          description: "Does the collection support lazy mint or not"
        minters:
          type: array
          description: "List of addresses that can mint items in this collection"
          items:
            "$ref": "#/components/schemas/Address"
        isRaribleContract:
          type: boolean

    NftCollectionStats:
      type: object
      properties:
        token:
          "$ref": "#/components/schemas/Address"
        totalItemSupply:
          "$ref": "#/components/schemas/BigInteger"
        totalOwnerCount:
          type: integer
        lastUpdatedAt:
          type: string
          format: date-time
      required:
        - token

    NftCollections:
      required:
        - collections
      type: object
      properties:
        total:
          type: integer
          deprecated: true
          description: Number of collections were found by request
          format: int64
        continuation:
          type: string
          description: Continuation token to paginate items search result
        collections:
          type: array
          description: List of found collections
          items:
            "$ref": "#/components/schemas/NftCollection"

    NftCollectionEvent:
      required:
        - eventId
        - id
      properties:
        eventId:
          type: string
        id:
          $ref: '#/components/schemas/Address'
        eventTimeMarks:
          # TODO make it mandatory in 1.43
          $ref: "#/components/schemas/EventTimeMarks"
      oneOf:
        - $ref: '#/components/schemas/NftCollectionUpdateEvent'
        - $ref: '#/components/schemas/NftCollectionSetBaseUriEvent'

    NftCollectionUpdateEvent:
      type: object
      required:
        - collection
      properties:
        type:
          type: string
          enum:
            - UPDATE
        collection:
          $ref: '#/components/schemas/NftCollection'

    NftCollectionSetBaseUriEvent:
      type: object
      properties:
        type:
          type: string
          enum:
            - SET_BASE_URI

    NftSignature:
      required:
        - r
        - s
        - v
      type: object
      properties:
        v:
          type: integer
        r:
          "$ref": "#/components/schemas/Binary"
        s:
          "$ref": "#/components/schemas/Binary"
    NftTokenId:
      required:
        - signature
        - tokenId
      type: object
      properties:
        tokenId:
          "$ref": "#/components/schemas/BigInteger"
        signature:
          "$ref": "#/components/schemas/NftSignature"

    NftItem:
      required:
        - id
        - contract
        - tokenId
        - creators
        - supply
        - lazySupply
      type: object
      properties:
        id:
          type: string
          description: Item identifier, has format '${contract}:${tokenId}'
        contract:
          "$ref": "#/components/schemas/Address"
        tokenId:
          "$ref": "#/components/schemas/BigInteger"
        creators:
          type: array
          description: Creators of the target item
          items:
            "$ref": "#/components/schemas/Part"
        supply:
          "$ref": "#/components/schemas/BigInteger"
        lazySupply:
          "$ref": "#/components/schemas/BigInteger"
        owners:
          type: array
          deprecated: true
          description: Owners of the target items
          items:
            "$ref": "#/components/schemas/Address"
        royalties:
          type: array
          deprecated: true
          description: Use a special endpoint '/v0.1/items/{itemId}/royalty'
          items:
            "$ref": "#/components/schemas/Part"
        lastUpdatedAt:
          type: string
          format: date-time
          description: "Datetime when the item was created"
        mintedAt:
          type: string
          format: date-time
          description: "Datetime when the item was minted"
        pending:
          type: array
          description: "Pending information about the item"
          items:
            "$ref": "#/components/schemas/ItemTransfer"
        deleted:
          type: boolean
          description: "Item was deleted or not"
        isRaribleContract:
          type: boolean
        isSuspiciousOnOS:
          type: boolean

    NftItemAttribute:
      required:
        - key
      type: object
      properties:
        key:
          type: string
        value:
          type: string
        type:
          type: string
        format:
          type: string
    NftItemRoyalty:
      required:
        - account
        - value
      type: object
      properties:
        account:
          "$ref": "#/components/schemas/Address"
        value:
          type: integer
    NftDeletedItem:
      required:
        - id
        - token
        - tokenId
      type: object
      properties:
        id:
          type: string
          description: Item identifier, has format '${contract}:${tokenId}'
        token:
          "$ref": "#/components/schemas/Address"
        tokenId:
          "$ref": "#/components/schemas/BigInteger"

    NftItemEvent:
      required:
        - eventId
        - itemId
      properties:
        eventId:
          type: string
        itemId:
          type: string
        eventTimeMarks:
          # TODO make it mandatory in 1.43
          $ref: "#/components/schemas/EventTimeMarks"
      oneOf:
        - $ref: "#/components/schemas/NftItemUpdateEvent"
        - $ref: "#/components/schemas/NftItemDeleteEvent"
    NftItemUpdateEvent:
      type: object
      required:
        - item
      properties:
        type:
          type: string
          enum:
            - UPDATE
        item:
          $ref: "#/components/schemas/NftItem"
    NftItemDeleteEvent:
      type: object
      required:
        - item
      properties:
        type:
          type: string
          enum:
            - DELETE
        item:
          $ref: "#/components/schemas/NftDeletedItem"

    NftItemMetaEvent:
      required:
        - eventId
        - itemId
      properties:
        eventId:
          type: string
        itemId:
          type: string
        eventTimeMarks:
          $ref: "#/components/schemas/EventTimeMarks"
      oneOf:
        - $ref: "#/components/schemas/NftItemMetaRefreshEvent"

    NftItemMetaRefreshEvent:
      type: object
      properties:
        type:
          type: string
          enum:
            - META_REFRESH

    NftItems:
      required:
        - items
      type: object
      properties:
        total:
          type: integer
          deprecated: true
          description: "The total number of items satisfy the query"
          format: int64
        continuation:
          type: string
          description: "Continuation token from the previous response"
        items:
          type: array
          description: "List of found items"
          items:
            "$ref": "#/components/schemas/NftItem"

    NftItemMeta:
      required:
        - name
        - tags
        - genres
        - content
        - status
      type: object
      properties:
        name:
          type: string
          description: "Name of the NFT item"
        description:
          type: string
          description: "Description of the NFT item"
        createdAt:
          type: string
          format: date-time
        tags:
          type: array
          default: [ ]
          items:
            type: string
        genres:
          type: array
          default: [ ]
          items:
            type: string
        language:
          type: string
        rights:
          type: string
        rightsUri:
          type: string
        externalUri:
          type: string
        attributes:
          type: array
          description: "Attributes of the NFT item"
          items:
            "$ref": "#/components/schemas/NftItemAttribute"
        content:
          type: array
          default: [ ]
          description: "NFT content information"
          items:
            $ref: "#/components/schemas/MetaContent"
        originalMetaUri:
          type: string
        status:
          $ref: "#/components/schemas/EthMetaStatus"

    EthCollectionMetaResult:
      required:
        - status
      properties:
        status:
          $ref: "#/components/schemas/EthMetaStatus"
        meta:
          $ref: "#/components/schemas/EthCollectionMeta"

    EthCollectionMeta:
      required:
        - name
        - tags
        - genres
        - content
      type: object
      properties:
        name:
          type: string
          description: "Name of the NFT collection"
        description:
          type: string
          description: "Description of the NFT collection"
        createdAt:
          type: string
          format: date-time
        tags:
          type: array
          default: [ ]
          items:
            type: string
        genres:
          type: array
          default: [ ]
          items:
            type: string
        language:
          type: string
        rights:
          type: string
        rightsUri:
          type: string
        externalUri:
          type: string
          description: "External link to the original website for the collection"
        originalMetaUri:
          type: string
        feeRecipient:
          "$ref": "#/components/schemas/Address"
        sellerFeeBasisPoints:
          type: integer
          format: int32
          deprecated: true
          description: "Indicates a 1% seller fee"
        content:
          type: array
          default: [ ]
          description: "NFT content information"
          items:
            $ref: "#/components/schemas/MetaContent"

    NftItemRoyaltyList:
      type: object
      properties:
        royalty:
          type: array
          items:
            "$ref": "#/components/schemas/NftItemRoyalty"

    MetaContent:
      type: object
      properties:
        fileName:
          type: string
        url:
          type: string
        representation:
          type: string
          enum:
            - PREVIEW
            - BIG
            - ORIGINAL
            - PORTRAIT
        mimeType:
          type: string
          example: "image/png"
        size:
          type: integer
          format: int64
      required:
        - url
        - representation

      oneOf:
        - $ref: "#/components/schemas/ImageContent"
        - $ref: "#/components/schemas/VideoContent"
        - $ref: "#/components/schemas/AudioContent"
        - $ref: "#/components/schemas/Model3dContent"
        - $ref: "#/components/schemas/HtmlContent"
        - $ref: "#/components/schemas/UnknownContent"

    ImageContent:
      type: object
      properties:
        "@type":
          type: string
          enum:
            - IMAGE
        width:
          type: integer
        height:
          type: integer

    VideoContent:
      type: object
      properties:
        "@type":
          type: string
          enum:
            - VIDEO
        width:
          type: integer
        height:
          type: integer

    AudioContent:
      type: object
      properties:
        "@type":
          type: string
          enum:
            - AUDIO

    Model3dContent:
      type: object
      properties:
        "@type":
          type: string
          enum:
            - MODEL_3D

    HtmlContent:
      type: object
      properties:
        "@type":
          type: string
          enum:
            - HTML

    UnknownContent:
      type: object
      properties:
        "@type":
          type: string
          enum:
            - UNKNOWN

    EthMetaStatus:
      type: string
      enum:
        - UNPARSEABLE_LINK
        - UNPARSEABLE_JSON
        - TIMEOUT
        - ERROR
        - OK

    LazyNft:
      type: object
      required:
        - contract
        - tokenId
        - uri
        - creators
        - royalties
        - signatures
      properties:
        contract:
          "$ref": "#/components/schemas/Address"
        tokenId:
          "$ref": "#/components/schemas/BigInteger"
        uri:
          type: string
          description: "Uniform Resource Identifier of the token"
        creators:
          type: array
          description: "Addresses of the NFT item creators"
          items:
            "$ref": "#/components/schemas/Part"
        royalties:
          type: array
          description: "List of royalties"
          items:
            "$ref": "#/components/schemas/Part"
        signatures:
          type: array
          description: "Digital signatures"
          items:
            "$ref": "#/components/schemas/Binary"
      description: Type of an Asset
      oneOf:
        - "$ref": "#/components/schemas/LazyErc721"
        - "$ref": "#/components/schemas/LazyErc1155"

    BurnLazyNftForm:
      type: object
      required:
        - creators
        - signatures
      properties:
        creators:
          type: array
          description: "Address of the NFT item creators"
          items:
            "$ref": "#/components/schemas/Address"
        signatures:
          type: array
          description: "Digital signatures"
          items:
            "$ref": "#/components/schemas/Binary"

    LazyErc1155:
      type: object
      required:
        - "@type"
        - supply
      properties:
        "@type":
          type: string
          enum:
            - ERC1155
        supply:
          "$ref": "#/components/schemas/BigInteger"
    LazyErc721:
      type: object
      required:
        - "@type"
      properties:
        "@type":
          type: string
          enum:
            - ERC721

    NftDeletedOwnership:
      required:
        - id
        - token
        - tokenId
        - owner
      type: object
      properties:
        id:
          type: string
          description: Ownership identifier, has format '${token}:${tokenId}:${owner}'
        token:
          "$ref": "#/components/schemas/Address"
        tokenId:
          "$ref": "#/components/schemas/BigInteger"
        owner:
          "$ref": "#/components/schemas/Address"
    NftOwnership:
      required:
        - id
        - contract
        - tokenId
        - owner
        - value
        - lazyValue
        - date
        - pending
      type: object
      properties:
        id:
          type: string
          description: Ownership identifier, has format '${token}:${tokenId}:${owner}'
        contract:
          "$ref": "#/components/schemas/Address"
        tokenId:
          "$ref": "#/components/schemas/BigInteger"
        owner:
          "$ref": "#/components/schemas/Address"
        creators:
          type: array
          deprecated: true
          description: Creators of the target item
          items:
            "$ref": "#/components/schemas/Part"
        value:
          "$ref": "#/components/schemas/BigInteger"
        lazyValue:
          "$ref": "#/components/schemas/BigInteger"
        date:
          type: string
          description: Start date of ownership
          format: date-time
        lastUpdatedAt:
          type: string
          format: date-time
        pending:
          type: array
          description: History of ownership
          items:
            "$ref": "#/components/schemas/ItemHistory"

    NftOwnershipEvent:
      required:
        - eventId
        - ownershipId
      properties:
        eventId:
          type: string
        ownershipId:
          type: string
        eventTimeMarks:
          # TODO make it mandatory in 1.43
          $ref: "#/components/schemas/EventTimeMarks"
        blockNumber:
          type: integer
          format: int64
      oneOf:
        - $ref: "#/components/schemas/NftOwnershipUpdateEvent"
        - $ref: "#/components/schemas/NftOwnershipDeleteEvent"
    NftOwnershipUpdateEvent:
      type: object
      required:
        - ownership
      properties:
        type:
          type: string
          enum:
            - UPDATE
        ownership:
          $ref: "#/components/schemas/NftOwnership"
    NftOwnershipDeleteEvent:
      type: object
      properties:
        type:
          type: string
          enum:
            - DELETE
        ownership:
          $ref: "#/components/schemas/NftDeletedOwnership"
        deletedOwnership:
          $ref: "#/components/schemas/NftOwnership"

    NftOwnerships:
      required:
        - ownerships
      type: object
      properties:
        total:
          type: integer
          deprecated: true
          description: Number of ownerships were found by request
          format: int64
        continuation:
          type: string
          description: Continuation token to paginate Ownerships search result
        ownerships:
          type: array
          description: List of found ownerships
          items:
            "$ref": "#/components/schemas/NftOwnership"

    NftItemIds:
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          description: "List of the items id"
          items:
            type: string

    NftOwnershipIds:
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          description: "List of the ownerships id"
          items:
            type: string

    DomainResolveResult:
        type: object
        required:
          - registrant
        properties:
          registrant:
            type: string
            description: "Domain registrant"