openapi: 3.0.3
info:
  title: OpenAPI definition
  version: v0.1

paths:
  "/v0.1/item/{itemId}/lock":
    post:
      tags:
        - lock-controller
      operationId: createLock
      parameters:
        - name: itemId
          description: "Item identifier, has format `${contract}:${tokenId}`"
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LockForm"
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Lock"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnlockableApiError"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnlockableApiError"
  "/v0.1/item/{itemId}/content":
    post:
      tags:
        - lock-controller
      operationId: getLockContent
      parameters:
        - name: itemId
          description: "Item identifier, has format `${contract}:${tokenId}`"
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SignatureForm"
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnlockableApiError"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnlockableApiError"
  "/v0.1/item/{itemId}/isUnlockable":
    get:
      tags:
        - lock-controller
      operationId: isUnlockable
      parameters:
        - name: itemId
          description: "Item identifier, has format `${contract}:${tokenId}`"
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnlockableApiError"
