openapi: 3.0.3
info:
  title: OpenAPI definition
  version: v0.1

paths:
  /v0.1/balances/eth/{owner}:
    get:
      tags:
        - balance-controller
      description: Return ETH balance
      operationId: getEthBalance
      parameters:
        - name: owner
          description: "Address of the ETH owner"
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Address'
      x-codeSamples:
        - lang: 'cURL'
          source: |
            curl --request GET \
            --url 'https://ethereum-api.rarible.org/v0.1/erc20/balances/eth/0x60f80121c31a0d46b5279700f9df786054aa5ee5'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EthBalance'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20IndexerApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20IndexerApiError'

  /v0.1/balances/{contract}/{owner}:
    get:
      tags:
        - balance-controller
      description: Return ERC20 token balance
      operationId: getErc20Balance
      parameters:
        - name: contract
          description: "Address of the contract"
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Address'
        - name: owner
          description: "Address of the ERC20 token owner"
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Address'
      x-codeSamples:
        - lang: 'cURL'
          source: |
            curl --request GET \
            --url 'https://ethereum-api.rarible.org/v0.1/erc20/balances/0x60f80121c31a0d46b5279700f9df786054aa5ee5/0x60f80121c31a0d46b5279700f9df786054aa5ee5'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20DecimalBalance'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20IndexerApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20IndexerApiError'

  /v0.1/balances/{contract}/{owner}/allowance:
    get:
      tags:
        - balance-controller
      description: Return ERC20 token allowance
      operationId: getErc20Allowance
      parameters:
        - name: contract
          description: "Address of the contract"
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Address'
        - name: owner
          description: "Address of the ERC20 token owner"
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Address'
      x-codeSamples:
        - lang: 'cURL'
          source: |
            curl --request GET \
            --url 'https://ethereum-api.rarible.org/v0.1/erc20/balances/0x60f80121c31a0d46b5279700f9df786054aa5ee5/0x60f80121c31a0d46b5279700f9df786054aa5ee5/allowance'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20DecimalBalance'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20IndexerApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20IndexerApiError'

  /v0.1/tokens/{contract}:
    get:
      tags:
        - erc20-token-controller
      description: Return ERC20 token balance by ID
      operationId: getErc20TokenById
      parameters:
        - name: contract
          description: "Address of the contract"
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Address'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20Token'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20IndexerApiError'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20IndexerApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erc20IndexerApiError'
