openapi: 3.0.3
info:
paths:

components:
  schemas:

    Lock:
      type: object
      required:
        - id
        - itemId
        - content
        - author
      properties:
        id:
          type: string
        itemId:
          type: string
          description: "Item identifier, has format `${contract}:${tokenId}`"
        content:
          type: string
        author:
          $ref: '#/components/schemas/Address'
        signature:
          $ref: '#/components/schemas/Binary'
        unlockDate:
          type: string
          format: date-time
          description: "Date and time when the content will be unlocked"
        version:
          type: integer
          format: int64

    LockForm:
      type: object
      required:
        - content
      properties:
        signature:
          $ref: '#/components/schemas/Binary'
        content:
          type: string

    SignatureForm:
      type: object
      required:
        - content
      properties:
        signature:
          $ref: '#/components/schemas/Binary'

    UnlockableApiError:
      required:
        - code
        - message
        - status
      type: object
      properties:
        status:
          type: integer
          format: int32
          description: "HTTP status code"
        code:
          type: string
          description: "Error type"
          enum:
            - UNKNOWN
            - LOCK_EXISTS
            - OWNERHIP_ERROR
        message:
          type: string
          description: "Error message"

    UnlockableEvent:
      required:
        - eventId
        - itemId
        - type
      type: object
      properties:
        eventId:
          type: string
        itemId:
          type: string
        type:
          type: string
          enum:
            - LOCK_CREATED
            - LOCK_UNLOCKED

    Address:
      type: string
      example: '0x60f80121c31a0d46b5279700f9df786054aa5ee5'

    Binary:
      type: string
