openapi: 3.0.3
info:
  title: OpenAPI definition
  version: v0.1

paths:
  "/v0.1/transactions":
    post:
      tags:
        - gateway-controller
      operationId: createGatewayPendingTransactions
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateTransactionRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/LogEvent"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GatewayApiError"

components:
  schemas:
    GatewayApiError:
      required:
        - code
        - message
        - status
      type: object
      properties:
        status:
          type: integer
          format: int32
        code:
          type: string
          enum:
            - UNKNOWN
            - VALIDATION
        message:
          type: string
